/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'
import { Route as AppPhysicsRouteImport } from './routes/app.physics'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppAnomalyIdRouteImport } from './routes/app.anomaly.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)
const AppPhysicsRoute = AppPhysicsRouteImport.update({
  id: '/physics',
  path: '/physics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppAnomalyIdRoute = AppAnomalyIdRouteImport.update({
  id: '/anomaly/$id',
  path: '/anomaly/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/problem': typeof ProblemRoute
  '/research': typeof ResearchRoute
  '/solution': typeof SolutionRoute
  '/team': typeof TeamRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/physics': typeof AppPhysicsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/': typeof AppIndexRoute
  '/app/anomaly/$id': typeof AppAnomalyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/problem': typeof ProblemRoute
  '/research': typeof ResearchRoute
  '/solution': typeof SolutionRoute
  '/team': typeof TeamRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/physics': typeof AppPhysicsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app': typeof AppIndexRoute
  '/app/anomaly/$id': typeof AppAnomalyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/problem': typeof ProblemRoute
  '/research': typeof ResearchRoute
  '/solution': typeof SolutionRoute
  '/team': typeof TeamRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/physics': typeof AppPhysicsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tracking': typeof AppTrackingRoute
  '/app/': typeof AppIndexRoute
  '/app/anomaly/$id': typeof AppAnomalyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/problem'
    | '/research'
    | '/solution'
    | '/team'
    | '/app/alerts'
    | '/app/physics'
    | '/app/settings'
    | '/app/tracking'
    | '/app/'
    | '/app/anomaly/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/problem'
    | '/research'
    | '/solution'
    | '/team'
    | '/app/alerts'
    | '/app/physics'
    | '/app/settings'
    | '/app/tracking'
    | '/app'
    | '/app/anomaly/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/problem'
    | '/research'
    | '/solution'
    | '/team'
    | '/app/alerts'
    | '/app/physics'
    | '/app/settings'
    | '/app/tracking'
    | '/app/'
    | '/app/anomaly/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProblemRoute: typeof ProblemRoute
  ResearchRoute: typeof ResearchRoute
  SolutionRoute: typeof SolutionRoute
  TeamRoute: typeof TeamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/physics': {
      id: '/app/physics'
      path: '/physics'
      fullPath: '/app/physics'
      preLoaderRoute: typeof AppPhysicsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anomaly/$id': {
      id: '/app/anomaly/$id'
      path: '/anomaly/$id'
      fullPath: '/app/anomaly/$id'
      preLoaderRoute: typeof AppAnomalyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppPhysicsRoute: typeof AppPhysicsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrackingRoute: typeof AppTrackingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnomalyIdRoute: typeof AppAnomalyIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppPhysicsRoute: AppPhysicsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrackingRoute: AppTrackingRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnomalyIdRoute: AppAnomalyIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ProblemRoute: ProblemRoute,
  ResearchRoute: ResearchRoute,
  SolutionRoute: SolutionRoute,
  TeamRoute: TeamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
